### PR TITLE
Release/ecmwf nomerge

### PR DESCRIPTION
**Pull request by corentincarton**
I would release this as a hot fix 3.1.2 or as a minor release 3.2.0. We have multiple fixes for the calibration code in this version and it also includes the new xarray reader for the water abstraction.

### CODE REVIEW

**Review by ecCinziaMazzetti — APPROVED** [review]
Fine by me!

**Review by StefaniaGrimaldi — APPROVED** [review]

**Review by doc78 — APPROVED** [review]
Everything seems ok. We updated the README file: please double check the Notes for Release 3.2.0 and add or modify anything you think should be included into this section.

**Comment by corentincarton** [comment]
@doc78 where can I find the release notes again? Confluence?

**Comment by doc78** [comment]
Release notes are in the README file, please check my last commit. Thanks. We will then make also a Confluence page.

**Comment by corentincarton** [comment]
@doc78, sorry I missed that commit. The release note looks fine! I would go ahead and merge it :)

**Pull request merged**
